# DevOps Task 01 - Jaideep.
# 1. Create a new workflow file under /.github/workflows or actions folder under /.github/actions, which will store changes to the GitHub Actions.
# For Example: /.github/workflows/deploy.yml)


name: Build & Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  call-sample:
    uses: ./.github/workflows/Sample.yml 
