# This is the Test File to Print Statement.
name: Sample Workflow

on:
  workflow_call:  # makes this file callable from other workflows

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message from Sample
        run: echo "Hello from Sample Workflow"
