# DevOps Task - Jaideep.
#  GitHub Actions to run storybook tests to make sure that those tests are passing with every PR.

name: StoryBook Test.
on:
  push:
    branches: [ "main" ] # Branch Name.

jobs:
  StoryBook-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository.
        uses: actions/checkout@v4

      - name: Setup Node JS.
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies.
        run: npm ci

      - name: Run StoryBook Tests.
        run: |
          echo "Let us Running the Stroy Book Test..."
          
