# DevOps Task - Jaideep.
#  https://github.com/jhanke00/next-product-site/issues/17
#  GitHub Actions to run storybook tests to make sure that those tests are passing with every PR.

name: StoryBook Test.
on:
  push:
    # branches: [ "main" ] # Branch Name. Commented for Now.

jobs:
  StoryBook-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository.
        uses: actions/checkout@v4

      - name: Setup Node JS.
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PNPM.
        run: npm install -g pnpm
        
      - name: Install Dependencies.
        run: pnpm install
        #npm i -g pnpm
        
      - name: Run Lint.
        run: pnpm lint
        
      - name: Build The Project
        run: pnpm build
        
      - name: Run StoryBook Tests.
        run: pnpm test
